from django.shortcuts import render
from django.http import HttpResponse
from django.db import connection
from django.contrib import messages
from .index import *
from .national_avg import *
from .time import *
from .top_10 import *
from .indicators import *
from .about import *
from .location import *
from .users import *
from .export_csv_file import *